import { useRef, useEffect } from "react";
import { cn } from "@/lib/utils";
import { Play, Image as ImageIcon, Box } from "lucide-react";
import { Badge } from "@/components/ui/badge";

export type MediaItem = {
    type: 'IMAGE' | 'VIDEO';
    source: 'CLOUDINARY' | 'YOUTUBE';
    url: string;
    variantName?: string;
};

interface ProductMediaGalleryProps {
    media: MediaItem[];
    activeIndex: number;
    onIndexChange: (index: number) => void;
}

export function ProductMediaGallery({ media, activeIndex, onIndexChange }: ProductMediaGalleryProps) {
    const scrollContainerRef = useRef<HTMLDivElement>(null);

    // Scroll to active thumbnail
    useEffect(() => {
        if (scrollContainerRef.current) {
            const thumbnail = scrollContainerRef.current.children[activeIndex] as HTMLElement;
            if (thumbnail) {
                thumbnail.scrollIntoView({ behavior: 'smooth', block: 'nearest', inline: 'center' });
            }
        }
    }, [activeIndex]);

    if (!media || media.length === 0) {
        return (
            <div className="aspect-square bg-neutral-100 rounded-xl flex items-center justify-center text-neutral-400 border border-neutral-200">
                <div className="flex flex-col items-center gap-2">
                    <ImageIcon className="w-12 h-12 opacity-30" />
                    <span className="text-sm">No Media Available</span>
                </div>
            </div>
        );
    }

    const selectedItem = media[activeIndex] || media[0];

    const getYoutubeId = (url: string) => {
        const regExp = /^.*(youtu.be\/|v\/|u\/\w\/|embed\/|watch\?v=|&v=)([^#&?]*).*/;
        const match = url.match(regExp);
        return (match && match[2].length === 11) ? match[2] : null;
    };

    const renderMainStage = () => {
        if (selectedItem.source === 'YOUTUBE') {
            const videoId = getYoutubeId(selectedItem.url);
            return (
                <iframe
                    className="w-full h-full rounded-xl bg-black"
                    src={`https://www.youtube.com/embed/${videoId}?autoplay=0&rel=0`}
                    title="YouTube video player"
                    frameBorder="0"
                    allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
                    allowFullScreen
                />
            );
        }

        if (selectedItem.type === 'VIDEO') {
            return (
                <video src={selectedItem.url} controls className="w-full h-full object-contain rounded-xl bg-black" />
            );
        }

        return (
            <img src={selectedItem.url} className="w-full h-full object-contain rounded-xl bg-white" />
        );
    };

    const getThumbnail = (item: MediaItem) => {
        if (item.source === 'YOUTUBE') {
            const videoId = getYoutubeId(item.url);
            return `https://img.youtube.com/vi/${videoId}/0.jpg`; // Valid Youtube Thumbnail
        }
        if (item.type === 'VIDEO') {
            // Cloudinary video thumbnail could be generated by changing extension to .jpg if using their SDK, 
            // but here we might just use a generic icon or the video poster if available.
            // For simplicity, let's assume the url ends in .mp4 and we can swap to .jpg for Cloudinary
            return item.url.replace(/\.(mp4|webm|mov)$/i, ".jpg");
        }
        return item.url;
    };

    return (
        <div className="flex flex-col gap-4 h-full">
            {/* Main Stage */}
            <div className="aspect-square w-full bg-neutral-50 border rounded-xl relative group overflow-hidden shadow-sm">
                {renderMainStage()}

                {/* Variant Name Badge */}
                {selectedItem.variantName && (
                    <div className="absolute top-4 left-4">
                        <Badge variant="secondary" className="backdrop-blur-md bg-white/80 text-neutral-900 border-white/20 shadow-sm pl-1 pr-3 py-1 flex items-center gap-1.5 pointer-events-none select-none">
                            <Box className="w-3.5 h-3.5 text-blue-500" />
                            {selectedItem.variantName}
                        </Badge>
                    </div>
                )}
            </div>

            {/* Thumbnails */}
            <div className="relative">
                <div
                    ref={scrollContainerRef}
                    className="flex gap-2 overflow-x-auto pb-2 scrollbar-thin scrollbar-thumb-neutral-200 scrollbar-track-transparent px-1"
                >
                    {media.map((item, idx) => (
                        <button
                            type="button"
                            key={idx}
                            onClick={() => onIndexChange(idx)}
                            className={cn(
                                "relative shrink-0 w-16 h-16 rounded-lg overflow-hidden border-2 transition-all duration-200 group focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-1",
                                activeIndex === idx
                                    ? "border-blue-600 ring-2 ring-blue-100 shadow-md scale-100 z-10"
                                    : "border-transparent opacity-60 hover:opacity-100 grayscale hover:grayscale-0"
                            )}
                        >
                            <img src={getThumbnail(item)} className="w-full h-full object-cover bg-neutral-100" />

                            {/* Icons overlay */}
                            {item.type === 'VIDEO' && (
                                <div className="absolute inset-0 bg-black/20 flex items-center justify-center">
                                    <div className="w-6 h-6 rounded-full bg-white/90 flex items-center justify-center shadow-sm">
                                        <Play className="w-3 h-3 text-black fill-current ml-0.5" />
                                    </div>
                                </div>
                            )}

                            {/* Variant Indicator dot */}
                            {item.variantName && (
                                <div className="absolute bottom-1 right-1 w-2 h-2 rounded-full bg-blue-500 border border-white shadow-sm" title={item.variantName} />
                            )}
                        </button>
                    ))}
                </div>
            </div>

            <div className="flex justify-between items-center text-xs text-neutral-400 px-1">
                <span>{activeIndex + 1} of {media.length}</span>
                <span>{selectedItem.source === 'CLOUDINARY' ? 'Uploaded Media' : 'YouTube content'}</span>
            </div>
        </div>
    );
}
